services:
  hotfoldermail:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs                 # logs visible on your host
      - C:/Users/Manuel/Documents/Auftrag:/mnt/daten
    restart: unless-stopped